### ISSUE TITLE
Todo Message 출력

### ISSUE THREAD

**Issue by Nabi-Yi** [Nabi-Yi/TodoApp#4]
###만들고자 하는 기능이 무엇인가요?
index page ("/") 접속 시 Hello 메시지 출력

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. [ ] RestController 기반 Controller 구현
2. [ ] Restful. get메서드 부분 구현
3. [ ] 필요한 내부 Service 구현

### 예상 작업 시간
1h
